# Generated by Django 4.0.6 on 2022-08-01 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventCoordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Happening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('duration', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[], max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.eventcoordinator')),
                ('performances', models.ManyToManyField(related_name='events_performances', to='events.happening')),
                ('rehearsals', models.ManyToManyField(related_name='events_rehearsals', to='events.happening')),
            ],
        ),
    ]
