# Generated by Django 4.0.6 on 2022-08-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[('1', 'Musical'), ('2', 'Play'), ('3', 'Dance'), ('4', 'Movie Night'), ('5', 'Presentation'), ('6', 'Open House')]),
        ),
    ]
