# Generated by Django 4.0.6 on 2022-08-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='archived',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Musical'), (2, 'Play'), (3, 'Dance'), (4, 'Movie Night'), (5, 'Presentation'), (6, 'Open House')]),
        ),
    ]
