# Generated by Django 4.0.6 on 2022-08-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_event_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
