# Generated by Django 4.0.6 on 2022-08-04 12:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0010_event_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='team',
            field=models.ManyToManyField(blank=True, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
    ]
