# Generated by Django 4.0.6 on 2022-08-03 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='common_role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Senior Member'), (2, 'Member'), (3, 'Applicant')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='role',
            name='unique_role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Teacher Sponsor'), (2, 'Technical Director'), (3, 'Technical Deputy Director')], null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.role'),
            preserve_default=False,
        ),
    ]
