# Generated by Django 4.0.6 on 2022-08-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='common_role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Senior Member'), (2, 'Member'), (3, 'Applicant')], null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='unique_role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Teacher Sponsor'), (2, 'Technical Director'), (3, 'Technical Deputy Director')], null=True, unique=True),
        ),
    ]
