# Generated by Django 4.0.6 on 2022-08-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_role_user_common_role_user_unique_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='unique_role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Teacher Sponsor'), (2, 'Technical Director'), (3, 'Technical Deputy Director')], unique=True),
        ),
    ]
