# Generated by Django 4.0.6 on 2022-08-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_unique_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.AlterField(
            model_name='user',
            name='common_role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Senior Member'), (2, 'Member'), (3, 'Applicant')], default=1),
            preserve_default=False,
        ),
    ]
